name: cache

on:
  push:
    branches: [ main ]

jobs:
  win32:
    runs-on: windows-2022
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules cache
        id: cache-node
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          lookup-only: true
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Restore pkg cache
        id: cache-pkg
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: ~/.pkg-cache
          lookup-only: 'true'
          key: ${{ runner.os }}-pkg-18
      - uses: actions/setup-node@v3
        if: steps.cache-node.outputs.cache-hit != 'true' || steps.cache-pkg.outputs.cache-hit != 'true'
        with:
          node-version: 18
      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true' || steps.cache-pkg.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Upload node_modules cache
        if: steps.cache-node.outputs.cache-hit != 'true'
        # DO not create cache on release, only on master
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install pkg-fetch
        if: steps.cache-pkg.outputs.cache-hit != 'true'
        run: yarn pkg-fetch

      - name: Upload pkg cache
        if: steps.cache-pkg.outputs.cache-hit != 'true'
        # DO not create cache on release, only on master
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.pkg-cache
          key: ${{ runner.os }}-pkg-18
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules cache
        id: cache-node
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          lookup-only: true
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Restore pkg cache
        id: cache-pkg
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: ~/.pkg-cache
          lookup-only: 'true'
          key: ${{ runner.os }}-pkg-18
      - uses: actions/setup-node@v3
        if: steps.cache-node.outputs.cache-hit != 'true' || steps.cache-pkg.outputs.cache-hit != 'true'
        with:
          node-version: 18
      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true' || steps.cache-pkg.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Upload node_modules cache
        if: steps.cache-node.outputs.cache-hit != 'true'
        # DO not create cache on release, only on master
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install pkg-fetch
        if: steps.cache-pkg.outputs.cache-hit != 'true'
        run: yarn pkg-fetch

      - name: Upload pkg cache
        if: steps.cache-pkg.outputs.cache-hit != 'true'
        # DO not create cache on release, only on master
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.pkg-cache
          key: ${{ runner.os }}-pkg-18
