name: release

on:
  release:
    types: [published]

jobs:
#  win32:
#    runs-on: windows-2022
#    permissions: write-all
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#      - name: Restore node_modules cache
#        id: cache-node
#        # DO not create cache on release, only on master
#        uses: actions/cache/restore@v4
#        with:
#          path: node_modules
#          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
#      - name: Install yarn deps
#        if: steps.cache-node.outputs.cache-hit != 'true'
#        run: yarn install --frozen-lockfile
#      - name: Restore pkg cache
#        id: cache-pkg
#        # DO not create cache on release, only on master
#        uses: actions/cache/restore@v4
#        with:
#          path: ~/.pkg-cache
#          key: ${{ runner.os }}-pkg-18
#      - name: Build
#        run: yarn build:win32
#
#      - name: Upload Release Asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ./http-remote-pc-control.exe
#          asset_name: http-remote-pc-control.exe
#          asset_content_type: application/vnd.microsoft.portable-executable
  docs:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore node_modules cache
        id: cache-node
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Generate swagger docs
        run: yarn schema:swagger
      - name: Upload swagger schema
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./swagger.json
          asset_name: swagger.json
          asset_content_type: application/json

  linux:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies # TODO cache
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libx11-dev libxtst-dev libxcb-ewmh-dev libxcb1-dev cmake g++ make libdbus-1-dev

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore node_modules cache
        id: cache-node
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Restore pkg cache
        id: cache-pkg
        # DO not create cache on release, only on master
        uses: actions/cache/restore@v4
        with:
          path: ~/.pkg-cache
          key: ${{ runner.os }}-pkg-18
      - name: Build
        run: yarn build:linux

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./http-remote-pc-control.elf
          asset_name: http-remote-pc-control.elf
          asset_content_type: application/x-executable

#  aur:
#    needs: [linux, win32, docs]
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - name: Copy PKGBUILD and related files
#        run: |
#          TAG=${{ github.event.release.tag_name }}
#          VERSION=$(jq -r '.version' package.json)
#          sed -i "s/^pkgver=.*/pkgver=${VERSION}/" ./packages/arch/PKGBUILD
#          sed -i "s/^tag=.*/tag=${TAG}/" ./packages/arch/PKGBUILD
#
#      - name: Publish to AUR
#        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
#        with:
#          pkgname: http-remote-pc-control
#          pkgbuild: ./packages/arch/PKGBUILD
#          assets: |
#            ./packages/arch/http-remote-pc-control.install
#            ./packages/http-remote-pc-control.service
#            ./packages/gen-certs.sh
#            ./san.cnf
#          commit_username: "GitHub Actions Bot"
#          updpkgsums: "true"
#          commit_email: "actions@github.com"
#          ssh_private_key: ${{ secrets.PK_ARCH }}
#          push_timeout: 1m

  deb:
    runs-on: ubuntu-22.04
    needs: [linux, win32, docs]
    steps:
      - uses: actions/checkout@v3
      - name: Download linux binary
        uses: actions/download-artifact@v5
        with:
          run-id: ${{ github.event.workflow_run.id }}
          pattern: |
            http-remote-pc-control.elf
            swagger.json
          path: /tmp/artifacts

      - name: Prepare package
        env:
          DEBEMAIL: "deathangel908@gmail.com"
          DEBFULLNAME: "Andrew Koidan"
        run: |
          VERSION=$(jq -r '.version' ./package.json)
          rootdir=$(pwd)
          srcdir="${rootdir}/packages/debian"
          pkgdir="${srcdir}/http-remote-pc-control"
          artifdir=/tmp/artifacts
          cd "$srcdir"
          sed -i "s/^Version:.*/Version: ${VERSION}/" "${srcdir}/control"
          install -D -m 644 "${srcdir}/control" "${pkgdir}/DEBIAN/control"
          install -D -m 755 "${artifdir}/http-remote-pc-control.elf" "${pkgdir}/usr/bin/http-remote-pc-control"
          install -D -m 644 "${artifdir}/swagger.json" "${pkgdir}/usr/share/http-remote-pc-control/swagger.json"
          install -D -m 644 "${rootdir}/packages/http-remote-pc-control.service" "${pkgdir}/usr/lib/systemd/user/http-remote-pc-control.service"
          install -D -m 755 "${rootdir}/packages/gen-certs.sh" "${pkgdir}/usr/share/http-remote-pc-control/gen-certs"
          install -D -m 644 "${rootdir}/san.cnf" "${pkgdir}/usr/share/http-remote-pc-control/san.cnf"
          dpkg-deb --build http-remote-pc-control http-remote-pc-control-amd64.deb

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: packages/debian/http-remote-pc-control
          asset_name: http-remote-pc-control.deb
          asset_content_type: application/vnd.debian.binary-package
